### PR TITLE
More readable version of a CoC section in a README

### PR DESCRIPTION
**Pull request by shurph**

### CODE REVIEW

**Comment by v-radelg** [comment]
Hello @shurph  , thank for your contribution. We are currently reviewing it. 

We will communicate the decision taken accordingly. Thanks for your time and support.  

Kind regards,  Microsoft C&E Localization Team

**Comment by LisandroSu** [comment]
Hello, @shurph 

Thank you for your feedback and suggestions.
 
This proposed file change has been accepted. The suggestion will be merged to this repository.  We will release this article on the next localization release round. 
 
Many thanks for your support.

Kind regards,

Microsoft C&E Localization Team

**Comment by olprod** [comment]
The PR is not being built because the target branch `live` is filtered in `.openpublishing.publish.config.json` on `live` branch.

**Comment by olprod** [comment]
The PR is not being built because the target branch `live` is filtered in `.openpublishing.publish.config.json` on `live` branch.

**Pull request merged**
